INSERT INTO Grupo(codigo_grupo, nome_grupo, tipo_item) VALUES 
(81, 'RECIPIENTES E MATERIAIS PARA ACONDICIONAMENTO E EMBALAGEM', 'material'),
(75, 'UTENSÍLIOS DE ESCRITÓRIO E MATERIAL DE EXPEDIENTE', 'material'),
(70, 'INFORMÁTICA - EQUIPAMENTOS,  PEÇAS, ACESSÓRIOS E SUPRIMENTOSDE TIC', 'material');
