INSERT INTO Classe(codigo_classe, nome_classe, codigo_grupo) VALUES 
(8135, 'MATERIAIS A GRANEL PARA ACONDICIONAMENTO E EMBALAGEM', 81), 
(7510, 'ARTIGOS PARA ESCRITÓRIO', 75),
(7090, 'SUPRIMENTOS DE INFORMÁTICA - TIC', 70);
