INSERT INTO Material(codigo_item, nome_material, descricao_item,
                      item_sustentavel, status, codigo_classe) VALUES 
(235329,'FITA ADESIVA EMBALAGEM', 
'FITA ADESIVA EMBALAGEM, MATERIAL: PAPEL , COMPRIMENTO: 50 M, LARGURA: 50 MM, APLICAÇÃO: EMPACOTAMENTO GERAL E REFORÇO PACOTES , COR: MARROM ',
false, true, 8135), 
(273427, 'BOBINA MÁQUINA CALCULAR', 
'BOBINA MÁQUINA CALCULAR, MATERIAL: PAPEL ACETINADO , GRAMATURA: 63 G/M2, COR: BRANCA , LARGURA: 69 MM, DIÂMETRO BOBINA: 60 MM',
false, true, 7510), 
(279313, 'CANETA MARCA-TEXTO', 'CANETA MARCA-TEXTO, MATERIAL: PLÁSTICO , TIPO PONTA: FLUORESCENTE , COR: AMARELA', 
false, true, 7510),
(228431, 'CARTUCHO TINTA IMPRESSORA HP', 'CARTUCHO TINTA IMPRESSORA HP, REFERÊNCIA CARTUCHO: HP C6625-A , REFERÊNCIA IMPRESSORA: DESKJET 840C , TIPO CARTUCHO: ORIGINAL , COR TINTA: COLORIDA , CAPACIDADE: 15 ML', false, true, 7090); 
